# Discord Bot - Development Configuration
# Run from root directory: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
# Includes live code mounting for development

services:
  discord-bot:
    # Environment configuration for development
    env_file:
      - .env.development  # Base development defaults
      - .env             # Local overrides (includes secrets like DISCORD_BOT_TOKEN)
      
    volumes:
      # Override the copied source code with live mounting for development
      - ./src:/app/src
      - ./prompts:/app/prompts
      - ./validate_config.py:/app/validate_config.py
      - ./run.py:/app/run.py
      - ./env_manager.py:/app/env_manager.py
      # System prompt templates and configuration for easy switching
      - ./config:/app/config
      
    environment:
      # Development-specific settings
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      
    # Enable hot-reloading by watching for changes
    command: >
      sh -c "
        echo '🔄 Development mode: watching for file changes...' &&
        python validate_config.py &&
        python -u run.py
      "
    
    # Ensure container rebuilds when source changes
    labels:
      - "dev.mode=true"
