# Development Hot Reload - Docker Compose Override
# Save as docker-compose.hotreload.yml

services:
  whisperengine-bot:
    volumes:
      # Mount source code for live editing
      - ./src:/app/src
      - ./prompts:/app/prompts
      - ./config:/app/config
      - ./run.py:/app/run.py
      - ./env_manager.py:/app/env_manager.py
      # Application data volumes (persistent)
      - bot_backups:/app/backups
      - bot_privacy:/app/privacy_data
      - bot_temp:/app/temp_images
      - bot_logs:/app/logs
      
    environment:
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      
    # Expose health check port for development
    ports:
      - "9090:9090"  # Health check endpoint
      
    # Use a file watcher for auto-restart
    command: >
      sh -c "
        echo '🔥 Hot reload mode: watching for Python changes...' &&
        pip install watchdog &&
        /home/appuser/.local/bin/watchmedo auto-restart --patterns='*.py' --recursive -- python -u run.py
      "
      
    labels:
      - "dev.hotreload=true"

# Volumes for hot reload mode
volumes:
  bot_backups:
    name: whisperengine-backups
    driver: local
  bot_privacy:
    name: whisperengine-privacy
    driver: local
  bot_temp:
    name: whisperengine-temp
    driver: local
  bot_logs:
    name: whisperengine-logs
    driver: local